# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constrainedClustering <- function(matrix, links, maxDistance, maxIterations, nRestarts) {
    .Call('_HiCDOC_constrainedClustering', PACKAGE = 'HiCDOC', matrix, links, maxDistance, maxIterations, nRestarts)
}

parseHic <- function(fname, resolution) {
    .Call('_HiCDOC_parseHic', PACKAGE = 'HiCDOC', fname, resolution)
}

